### ISSUE TITLE
Your documentation about docker deployment in readme doesn't work

### ISSUE THREAD

**Issue by WangShuXian6** [xAbdoAT/ChimeraGPT-WebUI#1]
Your documentation about docker deployment in readme doesn't work. 
Firstly,
```bash
docker pull xAbdoAT/ChimeraGPT-WebUI
```
is invalid because docker image names are not allowed to contain uppercase letters.

**Comment by xAbdoAT** [comment]
I'll look into it and u can host it on replit for now !
